### ISSUE TITLE
app\src\main\res\values\themes.xml:3:5-15:13: AAPT: error: resource color/purple_500 (aka com.example.restaurantfinder:color/purple_500) not found.     

### ISSUE THREAD

**Issue by ashharr** [tanya-555/RestaurantFinder#1]
Hey, I am getting this error while building. please help. 

`app\src\main\res\values\themes.xml:3:5-15:13: AAPT: error: resource color/purple_500 (aka com.example.restaurantfinder:color/purple_500) not found.
    `

**Comment by Ashapagal** [comment]
\values\themes.xml:3:5-15:13: AAPT: error: resource color
